version: '{build}-{branch}'
image: Visual Studio 2017
configuration: Release
environment:
  solution_name: Caliburn.Micro.Contrib.Controller
  solution_dir: '%APPVEYOR_BUILD_FOLDER%\src\'
  solution_file: '%solution_dir%%solution_name%.sln'
  project_name: '%solution_name%'
  project_dir: '%solution_dir%%project_name%\'
  project_file: '%project_dir%%project_name%.csproj'
  dynamicproxy_project_name: Caliburn.Micro.Contrib.Controller.DynamicProxy
  dynamicproxy_project_dir: '%solution_dir%%dynamicproxy_project_name%\'
  dynamicproxy_project_file: '%dynamicproxy_project_dir%%dynamicproxy_project_name%.csproj'
  extras_project_name: Caliburn.Micro.Contrib.Controller.Extras
  extras_project_dir: '%solution_dir%%extras_project_name%\'
  extras_project_file: '%extras_project_dir%%extras_project_name%.csproj'
  autofac_project_name: Caliburn.Micro.Contrib.Controller.Autofac
  autofac_project_dir: '%solution_dir%%autofac_project_name%\'
  autofac_project_file: '%autofac_project_dir%%autofac_project_name%.csproj'
install:
- cmd: choco install gitversion.portable -y
before_build:
- cmd: nuget restore "%solution_file%"
- cmd: gitversion /l console /output buildserver /updateAssemblyInfo
assembly_info:
  patch: false
build:
  project: '%solution_file%'
  publish_nuget: false
  publish_nuget_symbols: false
  verbosity: quiet
after_build:
- cmd: nuget pack "%project_file%" -properties "Configuration=%configuration%" -symbols -Exclude "**\FodyWeavers.xml"
- cmd: nuget pack "%dynamicproxy_project_file%" -properties "Configuration=%configuration%" -IncludeReferencedProjects -symbols -Exclude "**\FodyWeavers.xml"
- cmd: nuget pack "%extras_project_file%" -properties "Configuration=%configuration%" -IncludeReferencedProjects -symbols -Exclude "**\FodyWeavers.xml"
- cmd: nuget pack "%autofac_project_file%" -properties "Configuration=%configuration%" -IncludeReferencedProjects -symbols -Exclude "**\FodyWeavers.xml"
- cmd: appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\%project_name%.%GitVersion_NuGetVersion%.nupkg"
- cmd: appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\%project_name%.%GitVersion_NuGetVersion%.symbols.nupkg"
- cmd: appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\%dynamicproxy_project_name%.%GitVersion_NuGetVersion%.nupkg"
- cmd: appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\%dynamicproxy_project_name%.%GitVersion_NuGetVersion%.symbols.nupkg"
- cmd: appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\%extras_project_name%.%GitVersion_NuGetVersion%.nupkg"
- cmd: appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\%extras_project_name%.%GitVersion_NuGetVersion%.symbols.nupkg"
- cmd: appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\%autofac_project_name%.%GitVersion_NuGetVersion%.nupkg"
- cmd: appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\%autofac_project_name%.%GitVersion_NuGetVersion%.symbols.nupkg"
test: off
deploy:
- provider: NuGet
  name: MyGet
  server: https://www.myget.org/F/dittodhole/api/v2/package
  api_key:
    secure: c9r6oyxFOqnfj0xezZcLIoopgoBUb5ib9nrTYMkXDTqzvMrrXmprbHgyldag6NZ4
#  skip_symbols: true
  symbol_server: https://www.myget.org/F/dittodhole/symbols/api/v2/package
  on:
    branch: develop
- provider: NuGet
  name: NuGet
  api_key:
    secure: eKeaC+5KqtdxIqHjRQ8yJjK+z32hyfmuD5ZXPV4f2gLsafckIeyJGixpn9WnXbJm
#  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: NuGet (pre release)
  api_key:
    secure: eKeaC+5KqtdxIqHjRQ8yJjK+z32hyfmuD5ZXPV4f2gLsafckIeyJGixpn9WnXbJm
#  skip_symbols: true
  on:
    branch: /release\/.*/
